<?php

namespace AppBundle\Repository;
use AppBundle\Entity\RoadRoute;

/**
 * JourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourneyRepository extends \Doctrine\ORM\EntityRepository
{


    public function getJourneysByTime($route , $lowTime, $highTime){


        $query = $this->createQueryBuilder('j');
        $query = $query
            ->leftJoin('j.bus','b')
            ->where('b.route = :roadRoute')
            ->andWhere($query->expr()->between('j.startTime', ':lowTime', ':highTime'))
            ->setParameter('roadRoute', $route)
            ->setParameter('lowTime', $lowTime)
            ->setParameter('highTime', $highTime);

        $query=$query->getQuery();

        return $query->getResult();
    }

}
