<?php

namespace AppBundle\Repository;

/**
 * OwnerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
