<?php

namespace AppBundle\Repository;

/**
 * RouteCoordinateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteCoordinateRepository extends \Doctrine\ORM\EntityRepository
{
}
