<?php

namespace AppBundle\Repository;

/**
 * TrainStationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainStationRepository extends \Doctrine\ORM\EntityRepository
{
}
