<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TrainLine;

/**
 * TrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTrainsOfLine(TrainLine $trainLine){


        $query = $this->createQueryBuilder('t')
            ->where('t.isActive = :true')
            ->andWhere(':trainLine MEMBER OF t.trainLines')
            ->setParameter('true', true)
            ->setParameter('trainLine', $trainLine);

        $query=$query->getQuery();

        return $query->getResult();
    }


}
