<?php

namespace AppBundle\Repository;

/**
 * TrainLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainLineRepository extends \Doctrine\ORM\EntityRepository
{
}
