<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TrainLine;

/**
 * TrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTrainsOfLine(TrainLine $trainLine){


        $query = $this->createQueryBuilder('t')
            ->where('t.isActive = :true')
            ->leftJoin('t.trainLines', 'l', 'WITH', 'l.id = :myId')
            ->setParameter('true', true)
            ->setParameter('myId', $trainLine->getId());

        $query=$query->getQuery();

        return $query->getResult();
    }


}
