<?php

namespace AppBundle\Repository;

/**
 * WeekDayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekDayRepository extends \Doctrine\ORM\EntityRepository
{
}
